apiVersion: v1
kind: Service
metadata:
  name: node-app-service
  namespace: node-app
  labels:
    app: node-app
    tier: node-app-tier
spec:
  type: NodePort
  ports:
  - port: 8080
  selector:
    app: node-app
    tier: node-app-tier
